name: Practice garam

on:
  push:
    paths:
      - script.js

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  new_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "current file is canceled"
