name: Practice garam

on:
  push:
    paths:
      - script.js

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  new_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "current file is canceled"

      - name: Create dummy file
        run: echo "hello" > hello.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: hello.txt

  second_job:
    runs-on: ubuntu-latest
    needs: new_job
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with: 
          name: my-artifact
